### PR TITLE
add memory hooks for cheat/rumble

### PR DESCRIPTION
**Pull request by RetroSven**

### CODE REVIEW

**Comment by leiradel** [comment]
@RetroSven this patch doesn't make sense for this core. GW games are not emulations, they're simulations of the actual games, and are written in Lua. There's no such thing as system memory here. Even the save RAM is just an ASCII-based key/value store used to persist high scores, and not something that you can just peek a byte from and take some action upon it.

**Comment by RetroSven** [comment]
@leiradel it's persisted data - and if it's persisted it can be edited and then changed for cheating purposes.  Let's please put it back.  It's a value-add for the cheat system that's in RA now.

Also, let's please discuss things before reverting any more changes.  All three of these appear to be fine to me.

**Comment by leiradel** [comment]
It's persistent data, not system RAM. Lets not report it to the frontend as if it was system RAM. If persistent data is valuable for cheating, the cheating system must be able to access persistent data in **addition to** system RAM.

**Comment by leiradel** [comment]
It's a question of correctness. GW games does **not** have system RAM. If you want to access persistent "RAM" (inside double quotes because even this is not real emulated persistent RAM), access it via `retro_get_memory_data/size` with the correct type: `RETRO_MEMORY_SAVE_RAM`.

**Comment by leiradel** [comment]
I wonder how you plan to access system or persistent RAM for other cores that are also not emulators. You can't just force cheats into these kind of cores the same way you do for emulators.

**Comment by twinaphex** [comment]
@RetroSven , yeah these cores are joint-shared with @leiradel in terms of ownership, so I am not the one calling all the shots for these three cores (gw-libretro, 81 and fuse). So let's just try and see if both sides can find a compromise here that both can live with.

**Comment by leiradel** [comment]
It's not really difficult. The ZX81 core only emulates the 48 Kb model for now, so it's just a question of returning the correct memory count at the correct offset to disregard the ROM.

The Fuse core is more involved, since it emulates many models, each with a different RAM size. But it's doable, no questions. Here it's also important not to return ROM as if it was RAM.
The GW core is different, it doesn't have System RAM. The Save RAM is already being reported, so cheats can use that for whatever they want without any changes to the core.

**Comment by leiradel** [comment]
If we implement the memory hooks wrongly, anything that relies on them later down the road will have unpleasant surprises, and workarounds will have to be put in place. The correct thing to do is to implement the memory hooks correctly.

**Comment by leiradel** [comment]
I can try and help @RetroSven, I'm even personally interested in having memory hooks for the 81 and Fuse cores.

**Comment by RetroSven** [comment]
re: gw - I would argue that SRAM is a subset of system RAM.  It's a form of RAM and it's part of the system in its entirety.  If SRAM is the only kind of RAM that GW has, then it's proper and correct to also return it for RETRO_MEMORY_SYSTEM_RAM.  

re: implementing incorrectly - it is your opinion that it is incorrect.  In my opinion it is not.  I stand by the argument that "system" can mean emulated system or emulator system.  If the latter, then essentially any variable is up for grabs.  Please provide a real-world scenario where unpleasant surprises could result from this code.  Note that it should be realistic and plausible.  Worrying about every little eventuality is a recipe for stagnation. Even if any theoretical issue arose in the future, it can very likely be dealt with quickly.  In the meantime, people get added enjoyment.

As for updating the fuse/81 code - I wish you would have just done that in the first place.  It's perfectly acceptable to leave the existing code in place until you or someone else decides to tweak it to make it more to your personal liking.  Unilaterally and heavy-handedly retracting submissions is not a way to foster a sense of community.  You're making it pretty clear that these projects are "yours".  So have at it.  You have successfully turned off my interest in them.

**Comment by fr500** [comment]
As you said it yourself, these cores are his, and he should have veto power on what gets merged or not.

**Comment by leiradel** [comment]
> re: gw - I would argue that SRAM is a subset of system RAM.

Except that it's not. Save RAM was originally a separate, battery backed, on-cartridge RAM chip totally separated from System RAM. The libretro API keeps this distinction clear, and provides `RETRO_MEMORY_SYSTEM_RAM` for when you want the System RAM, and `RETRO_MEMORY_SAVE_RAM` for when you want the persistent RAM.

> it's proper and correct to also return it for RETRO_MEMORY_SYSTEM_RAM.

It's not, gw-libretro only has persistent RAM, which is **not** System RAM.

> re: implementing incorrectly - it is your opinion that it is incorrect.

It's not my opinion, it's the libretro API, whether you like it or not. Please see the description of the `RETRO_MEMORY_*` defines in `libretro.h`.

> I stand by the argument that "system" can mean emulated system or emulator system.

Except that this is **not** the intent of the libretro API.

> Please provide a real-world scenario where unpleasant surprises could result from this code.

Sorry, but no. I stand correct, if you have doubts about the libretro API and don't believe my word please try to clear that up in the Discord channels.

> it can very likely be dealt with quickly.

It's a very naive thing to believe this. If the thing is wrong but is already used everywhere, the cost of changing will be huge, so everything else will have to adapt too.

> I wish you would have just done that in the first place.

Not until it's correct.

> It's perfectly acceptable to leave the existing code in place until you or someone else decides to tweak it

No it's not. If it stays wrong for too long, it'll likely stay wrong forever, or require a huge effort to correct.

> to make it more to your personal liking.

It's not my personal liking. Please talk to other libretro devs about the libretro API. The very success of the API and of RetroArch is because we don't tamper with it to implement the new-cool-functionality-of-the-day.

> Unilaterally and heavy-handedly retracting submissions is not a way to foster a sense of community.

Again, take a look at the API before submitting code that uses it. When the code is right, I'll gladly merge the PR.

> You're making it pretty clear that these projects are "yours". So have at it. You have successfully turned off my interest in them.

They're not mine, but they were my creations and I'm the main (only?) maintainer. I'll gladly merge all PRs that are correct in the libretro API usage and that brings value to them and to RetroArch.

**Comment by twinaphex** [comment]
Hi RetroSven- please email me at libretro@gmail.com and maybe I can be a mediator between you two for these two opposing schools of thought. I really hope we can find a solution here that caters to both camps - it's just that both sides want to do something with their own interfaces and I believe that with the right communication and diplomacy, we can both get what we want here.

I will repeat again - I respect both of you guys greatly. Please let's not fight here.

**Comment by RetroSven** [comment]
> because it'll come back to bite us in the future.

Unless you can come up with a real/practical example that's just FUD.

**Comment by leiradel** [comment]
Read my comment elsewhere, we already have plans that will use the memory APIs. Despite that, they should be implemented correctly. Try to understand something before trying to implement it.

**Comment by twinaphex** [comment]
> Try to understand something before trying to implement it.

Can we please not make these remarks? These are not helpful or particularly welcome to the other contributors.

Let's both cool down here, by the conversation already having reached this stage it shows that there is nothing beneficial/positive to be accomplished anymore so we need to mitigate any further damage that can be done right now.

**Comment by leiradel** [comment]
Yeah, I'm sorry. I'm glad that everyone now understands the importance of sticking to the API. It's better for everyone that needs/will need to use it.

**Pull request merged**
